nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome..')
print('Seu nome em maiúculos é {}' .format(nome.upper()))
print('Seu nome em minúsculos é {}' .format(nome.lower()))
print('Se nome tem ao todo {} letras' .format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras ' .format(nome.find(' ')))